<?php
/*
+--------------------------------------------------------------------+
| CiviCRM version 4.6                                                |
+--------------------------------------------------------------------+
| Copyright CiviCRM LLC (c) 2004-2015                                |
+--------------------------------------------------------------------+
| This file is a part of CiviCRM.                                    |
|                                                                    |
| CiviCRM is free software; you can copy, modify, and distribute it  |
| under the terms of the GNU Affero General Public License           |
| Version 3, 19 November 2007 and the CiviCRM Licensing Exception.   |
|                                                                    |
| CiviCRM is distributed in the hope that it will be useful, but     |
| WITHOUT ANY WARRANTY; without even the implied warranty of         |
| MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.               |
| See the GNU Affero General Public License for more details.        |
|                                                                    |
| You should have received a copy of the GNU Affero General Public   |
| License and the CiviCRM Licensing Exception along                  |
| with this program; if not, contact CiviCRM LLC                     |
| at info[AT]civicrm[DOT]org. If you have questions about the        |
| GNU Affero General Public License or the licensing of CiviCRM,     |
| see the CiviCRM license FAQ at http://civicrm.org/licensing        |
+--------------------------------------------------------------------+
 */
/**
 * @package CRM
 * @copyright CiviCRM LLC (c) 2004-2015
 *
 * Generated from xml/schema/CRM/Civisocial/CivisocialUser.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 */
require_once 'CRM/Core/DAO.php';
require_once 'CRM/Utils/Type.php';
class CRM_Civisocial_DAO_CivisocialUser extends CRM_Core_DAO {
	/**
	 * static instance to hold the table name
	 *
	 * @var string
	 */
	static $_tableName = 'civisocial_user';
	/**
	 * static instance to hold the field values
	 *
	 * @var array
	 */
	static $_fields = null;
	/**
	 * static instance to hold the keys used in $_fields for each field.
	 *
	 * @var array
	 */
	static $_fieldKeys = null;
	/**
	 * static instance to hold the FK relationships
	 *
	 * @var string
	 */
	static $_links = null;
	/**
	 * static instance to hold the values that can
	 * be imported
	 *
	 * @var array
	 */
	static $_import = null;
	/**
	 * static instance to hold the values that can
	 * be exported
	 *
	 * @var array
	 */
	static $_export = null;
	/**
	 * static value to see if we should log any modifications to
	 * this table in the civicrm_log table
	 *
	 * @var boolean
	 */
	static $_log = false;
	/**
	 * Unique User ID
	 *
	 * @var int unsigned
	 */
	public $id;
	/**
	 * FK to Contact ID that owns that account
	 *
	 * @var int unsigned
	 */
	public $contact_id;
	/**
	 * Backend OAuth Provider
	 *
	 * @var string
	 */
	public $backend;
	/**
	 * User ID for facebook, to be used to match friends etc.
	 *
	 * @var string
	 */
	public $social_user_id;
	/**
	 * Access Token Provided by OAuth Provider
	 *
	 * @var string
	 */
	public $access_token;
	/**
	 * Access Token Provided by OAuth Provider
	 *
	 * @var string
	 */
	public $oauth_object;
	/**
	 * When was the civisocial user was created.
	 *
	 * @var timestamp
	 */
	public $created_date;
	/**
	 * When was the the civisocial user was created or modified or deleted.
	 *
	 * @var timestamp
	 */
	public $modified_date;
	/**
	 * class constructor
	 *
	 * @return civisocial_user
	 */
	function __construct() {
		$this->__table = 'civisocial_user';
		parent::__construct();
	}
	/**
	 * Returns foreign keys and entity references
	 *
	 * @return array
	 *   [CRM_Core_Reference_Interface]
	 */
	static function getReferenceColumns() {
		if (!self::$_links) {
			self::$_links = static::createReferenceColumns(__CLASS__);
			self::$_links[] = new CRM_Core_Reference_Basic(self::getTableName(), 'contact_id', 'civicrm_contact', 'id');
		}
		return self::$_links;
	}
	/**
	 * Returns all the column names of this table
	 *
	 * @return array
	 */
	static function &fields() {
		if (!(self::$_fields)) {
			self::$_fields = array(
				'id' => array(
					'name' => 'id',
					'type' => CRM_Utils_Type::T_INT,
					'title' => ts('Civisocial User ID'),
					'description' => 'Unique User ID',
					'required' => true,
					'import' => true,
					'where' => 'civisocial_user.id',
					'headerPattern' => '',
					'dataPattern' => '',
					'export' => true,
				),
				'contact_id' => array(
					'name' => 'contact_id',
					'type' => CRM_Utils_Type::T_INT,
					'title' => ts('Contact ID'),
					'description' => 'FK to Contact ID that owns that account',
					'FKClassName' => 'CRM_Contact_DAO_Contact',
				),
				'backend' => array(
					'name' => 'backend',
					'type' => CRM_Utils_Type::T_STRING,
					'title' => ts('Backend'),
					'description' => 'Backend OAuth Provider',
					'maxlength' => 128,
					'size' => 30,
					'export' => true,
					'where' => 'civisocial_user.backend',
					'headerPattern' => '',
					'dataPattern' => '',
					'html' => array(
						'type' => 'Text',
					),
				),
				'social_user_id' => array(
					'name' => 'social_user_id',
					'type' => CRM_Utils_Type::T_STRING,
					'title' => ts('Social User ID'),
					'description' => 'User identifier given by Social Media, to be used to match friends etc.',
					'required' => false,
					'maxlength' => 128,
					'size' => 128,
					'export' => true,
					'where' => 'civisocial_user.social_user_id',
					'headerPattern' => '',
					'dataPattern' => '',
					'default' => 'NULL',
				),
				'access_token' => array(
					'name' => 'access_token',
					'type' => CRM_Utils_Type::T_STRING,
					'title' => ts('Access Token provided by OAuth Provider'),
					'description' => 'Access Token Provided by OAuth Provider',
					'required' => false,
					'maxlength' => 511,
					'size' => 511,
					'export' => true,
					'where' => 'civisocial_user.access_token',
					'headerPattern' => '',
					'dataPattern' => '',
					'default' => 'NULL',
				),
				'oauth_object' => array(
					'name' => 'oauth_object',
					'type' => CRM_Utils_Type::T_STRING,
					'title' => ts('Serialized Object returned by OAuth Provider'),
					'description' => 'Access Token Provided by OAuth Provider',
					'required' => false,
					'maxlength' => 1023,
					'size' => 1023,
					'export' => true,
					'where' => 'civisocial_user.oauth_object',
					'headerPattern' => '',
					'dataPattern' => '',
					'default' => 'NULL',
				),
				'created_date' => array(
					'name' => 'created_date',
					'type' => CRM_Utils_Type::T_DATE,
					'title' => ts('Created Date'),
					'description' => 'When was the civisocial user was created.',
					'required' => false,
					'export' => true,
					'where' => 'civisocial_user.created_date',
					'headerPattern' => '',
					'dataPattern' => '',
				),
				'modified_date' => array(
					'name' => 'modified_date',
					'type' => CRM_Utils_Type::T_DATE,
					'title' => ts('Modified Date'),
					'description' => 'When was the the civisocial user was created or modified or deleted.',
					'required' => false,
					'export' => true,
					'where' => 'civisocial_user.modified_date',
					'headerPattern' => '',
					'dataPattern' => '',
				),
			);
		}
		return self::$_fields;
	}
	/**
	 * Returns an array containing, for each field, the arary key used for that
	 * field in self::$_fields.
	 *
	 * @return array
	 */
	static function &fieldKeys() {
		if (!(self::$_fieldKeys)) {
			self::$_fieldKeys = array(
				'id' => 'id',
				'contact_id' => 'contact_id',
				'backend' => 'backend',
				'social_user_id' => 'social_user_id',
				'access_token' => 'access_token',
				'oauth_object' => 'oauth_object',
				'created_date' => 'created_date',
				'modified_date' => 'modified_date',
			);
		}
		return self::$_fieldKeys;
	}
	/**
	 * Returns the names of this table
	 *
	 * @return string
	 */
	static function getTableName() {
		return self::$_tableName;
	}
	/**
	 * Returns if this table needs to be logged
	 *
	 * @return boolean
	 */
	function getLog() {
		return self::$_log;
	}
	/**
	 * Returns the list of fields that can be imported
	 *
	 * @param bool $prefix
	 *
	 * @return array
	 */
	static function &import($prefix = false) {
		if (!(self::$_import)) {
			self::$_import = array();
			$fields = self::fields();
			foreach ($fields as $name => $field) {
				if (CRM_Utils_Array::value('import', $field)) {
					if ($prefix) {
						self::$_import['al_user'] = &$fields[$name];
					} else {
						self::$_import[$name] = &$fields[$name];
					}
				}
			}
		}
		return self::$_import;
	}
	/**
	 * Returns the list of fields that can be exported
	 *
	 * @param bool $prefix
	 *
	 * @return array
	 */
	static function &export($prefix = false) {
		if (!(self::$_export)) {
			self::$_export = array();
			$fields = self::fields();
			foreach ($fields as $name => $field) {
				if (CRM_Utils_Array::value('export', $field)) {
					if ($prefix) {
						self::$_export['al_user'] = &$fields[$name];
					} else {
						self::$_export[$name] = &$fields[$name];
					}
				}
			}
		}
		return self::$_export;
	}
}
