<?php

return array(
    'enable_facebook' => array(
        'group_name' => 'CiviSocial Account Credentials',
        'group' => 'civisocial',
        'name' => 'enable_facebook',
        'type' => 'Boolean',
        'is_domain' => 1,
        'is_contact' => 0,
        'default' => false,
        'title' => 'Use Facebook OAuth?',
        'description' => 'Enable User Authentication via Facebook',
        'help_text' => '',
        'html_type' => 'CheckBox',
        'quick_form_type' => 'YesNo',
        ),
    'facebook_app_id' => array(
        'group_name' => 'CiviSocial Account Credentials',
        'group' => 'civisocial',
        'name' => 'facebook_app_id',
        'type' => 'String',
        'is_domain' => 1,
        'is_contact' => 0,
        'title' => 'Facebook AppId',
        'description' => 'Facebook Application ID',
        'help_text' => 'Appid for facebook app. Please look <a href="https://developers.facebook.com/docs/facebook-login/login-flow-for-web/v2.3">here</a> for more details.',
        'html_type' => 'Text',
        'quick_form_type' => 'Element',
        ),
    'facebook_secret' => array(
        'group_name' => 'CiviSocial Account Credentials',
        'group' => 'civisocial',
        'name' => 'facebook_secret',
        'type' => 'String',
        'is_domain' => 1,
        'is_contact' => 0,
        'title' => 'Facebook Secret',
        'description' => 'Facebook Application Secret',
        'help_text' => 'Application Secret for facebook.',
        'html_type' => 'Text',
        'quick_form_type' => 'Element',
        ),
    'enable_googleplus' =>array(
        'group_name' => 'CiviSocial Account Credentials',
        'group' => 'civisocial',
        'name' => 'enable_googleplus',
        'type' => 'Boolean',
        'is_domain' => 1,
        'is_contact' => 0,
        'default' => false,
        'title' => 'Use Google Plus OAuth?',
        'description' => 'Enable User Authentication via Google Plus',
        'help_text' => '',
        'html_type' => 'CheckBox',
        'quick_form_type' => 'YesNo',
        ),
    'google_plus_key' => array(
        'group_name' => 'CiviSocial Account Credentials',
        'group' => 'civisocial',
        'name' => 'google_plus_key',
        'type' => 'String',
        'is_domain' => 1,
        'is_contact' => 0,
        'title' => 'Google Plus Key',
        'description' => 'Google Plus Application Key',
        'help_text' => 'Google Plus OAuth Key',
        'html_type' => 'Text',
        'quick_form_type' => 'Element',
        ),
    'google_plus_secret' => array(
        'group_name' => 'CiviSocial Account Credentials',
        'group' => 'civisocial',
        'name' => 'google_plus_secret',
        'type' => 'String',
        'is_domain' => 1,
        'is_contact' => 0,
        'title' => 'Google Plus Secret',
        'description' => 'Google Plus Application Secret',
        'help_text' => 'Google Plus OAuth Secret',
        'html_type' => 'Text',
        'quick_form_type' => 'Element',
        ),
    );